apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "syslogserver.fullname" . }}
  labels:
    app: {{ include "syslogserver.fullname" . }}
  {{- if .Values.serviceAccount.annotations }}
annotations:
  {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
  {{- end }}